### ISSUE TITLE
当我滑动到两个图片的中间时，执行手势图片的扩大，会崩溃掉

### ISSUE THREAD

**Issue by gandesheng** [byc4426/ImageWatcher#6]
java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2072)
        at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2235)
        at byc.imagewatcher.ImageWatcher.onScroll(ImageWatcher.java:346)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:622)
        at byc.imagewatcher.ImageWatcher.onTouchEvent(ImageWatcher.java:264)

**Comment by byc4426** [comment]
暂时用   try {  }catch (){ }包裹起来吧
            try {
                vPager.onTouchEvent(e2);
            }catch (IllegalArgumentException e){
            }
